name: BLRTransitApp
options:
  bundleIdPrefix: com.blrtransit
  deploymentTarget:
    iOS: "17.0"

targets:
  BLRTransitApp:
    type: application
    platform: iOS
    sources:
      - BLRTransitApp
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.blrtransit.app
        INFOPLIST_FILE: BLRTransitApp/App/Info.plist
        GENERATE_INFOPLIST_FILE: NO
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
